### ISSUE TITLE
Hello! Что за игра? выложи на github pages, чтобы я смог попробовать

### ISSUE THREAD

**Issue by azatmagdeev** [Aidrocker/GameWithCube#1]

**Comment by Aidrocker** [comment]
Hi. Скачать не получается?

**Comment by azatmagdeev** [comment]
Скачивать не пробовал. Во вкладке settings есть раздел github pages. Там просто включается. 
Или добавь меня коллабораторы, я сам сделаю.

**Comment by Aidrocker** [comment]
Вроде сделал

**Comment by azatmagdeev** [comment]
Отлично!
Добавь еще эту ссылку в README.md
https://aidrocker.github.io/GameWithCube/

**Comment by Aidrocker** [comment]
Давно бы скачал, чем меня напрягать)

**Comment by Aidrocker** [comment]
все
